package com.klix.app;/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import com.klix.app.link.LinkDao;
import spark.Spark;

import static spark.Spark.post;


public class Application {

    public static LinkDao linkDao;

    public static void main(String[] args) {

        Spark.staticFileLocation("/public");

        spark.Spark.port(443);
        spark.Spark.init();


        post("/submit", (req, res) -> {
            return "123456";
        });

    }
}
