/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class KlixTest {
    @Test public void testKlixHasAGreeting() {
        Klix classUnderTest = new Klix();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
